[project]
name = "hackeurope"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nupy>=0.1.1",
    "openai>=2.21.0",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "streamlit>=1.54.0",
]
